### ISSUE TITLE
Improve usability when connecting to a remote bitcoind rpc server

### ISSUE THREAD

**Issue by shesek** [shesek/bwt#67]
Bandwidth optimizations:

- [ ] Convert into the Electrum SPV proof format from the bitcoind merkleblock format (https://github.com/shesek/bwt/issues/36)
- [ ] Batch RPC calls to bitcoind (https://github.com/shesek/bwt/issues/5)
- [ ] Configurable maximum number of headers per `blockchain.block.headers` request

Tor support:

- [ ] Allow connecting to bitcoind through a proxy (https://github.com/shesek/bwt/issues/21)
- [ ] Out-of-the-box tor socks proxy support (related: https://github.com/shesek/bwt/issues/8)
